### ISSUE TITLE
Automated session F.M.

### ISSUE THREAD

**Issue by DrArcularis** [fallenangel42/electron#14]
Randomly enable Frequency Modulation in an automated session

**Comment by fallenangel42** [comment]
Do you have some ideas about how that could be implemented in order to generate pleasant results? There are, in my experience, two possible ways to use FM. One is for advanced triphase effects, as the phase between the two signals will change in interesting ways with FM enabled, and the other one is for creating "squeezing" sensations (so then better suited for 2 independent channels).

**Comment by fallenangel42** [comment]
@DrArcularis Let me know if you have some ideas about this (see comment above). Thank you!

**Comment by DrArcularis** [comment]
As I have become more experienced driving with electron, I agree that it random FM would have little added value, and useful FM effects would only apply for triphase or 2 independent channels (but not both), so closing the issue.
